#!/usr/bin/python

import os
import sys

def parse(config):
    fd = open(config)
    tmp = {}
    for i in fd:
        i = i.strip()
        if i.startswith('#'):
            pass
        elif len(i) == 0:
            pass
        else:
            (key, value) = i.split('=', 2)
            tmp[key] = value
    fd.close()
    return tmp

def diff(a, b):
    return filter(lambda i: i not in b, a.iterkeys())

def common(a, b):
    return filter(lambda i: i in b, a.iterkeys())

def action_multi(fun, args):
    (f1, f2) = map(parse, args)
    c = fun(f1, f2)
    c.sort()
    for i in c:
        print "%s=%s" % (i, f1[i])

if __name__ == "__main__":
    args = sys.argv[1:]
    cmd = args[0]
    if cmd == "base":
        action_multi(common, args[1:])
    if cmd == "diff":
        action_multi(diff, args[1:])
