#!/usr/bin/python

import os
import sys

def parse(config):
    """parse a kernel config file into a dict"""
    fd = open(config)
    tmp = {}
    for i in fd:
        i = i.strip()
        if i.startswith('#'):
            if i.endswith(' is not set'):
                i = i[2:]
                (key, none) = i.split(' ', 1)
                tmp[key] = None
        elif len(i) == 0:
            pass
        else:
            (key, value) = i.split('=', 1)
            tmp[key] = value
    fd.close()
    return tmp

def print_value(k, v):
    """print config entry"""
    if v == None:
        print "# %s is not set" % k
    else:
        print "%s=%s" % (k, v)

def diff(a, b):
    return filter(lambda i: i not in b, a.iterkeys())

def common(a, b):
    return filter(lambda i: i in b, a.iterkeys())

def action_multi(fun, args):
    (f1, f2) = map(parse, args)
    c = fun(f1, f2)
    c.sort()
    for i in c:
        print_value(i, f1[i])

if __name__ == "__main__":
    args = sys.argv[1:]
    cmd = args[0]
    if cmd == "base":
        action_multi(common, args[1:])
    if cmd == "diff":
        action_multi(diff, args[1:])
