#!/usr/bin/python
# usage (as root):
# echo 'n' | apt-get upgrade |./bloatscanner |sort -g -k3 |tail -n50

import sys
import os
import apt


def read_package_names(input):
    packages = []
    for i in input:
        if i.startswith('  '):
            packages.extend(i.split())
        else:
            break
    return packages

def get_package_infos(packages):
    # infos = {name:[deb-size delta, unpacked-size delta], ...}
    infos = {}
    cache = apt.Cache()
    for i in packages:
        p = cache[i]
        r = p.candidateRecord
        infos[i] = [int(r['Size']) - p.packageSize, int(r['Installed-Size'])*1024 - p.installedSize]
    return infos

def show_bloat(infos):
    for i in infos:
        (dsize, dusize) = infos[i]
        print i, dsize/1024, dusize/1024

for i in sys.stdin:
    if i.startswith('The following packages will be upgraded:'):
        packages = read_package_names(sys.stdin)
        infos = get_package_infos(packages)
        show_bloat(infos)
        break
